name: Bump Version & Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read current version
        id: ver
        run: |
          current=$(cat VERSION)
          echo "current=$current" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        run: |
          current="${{ steps.ver.outputs.current }}"
          bump="${{ github.event.inputs.bump }}"

          IFS=. read -r major minor patch <<< "$current"

          case "$bump" in
            major) major=$((major+1)); minor=0; patch=0 ;;
            minor) minor=$((minor+1)); patch=0 ;;
            patch) patch=$((patch+1)) ;;
          esac

          new="$major.$minor.$patch"
          echo "$new" > VERSION
          echo "new=$new" >> $GITHUB_OUTPUT

      - name: Commit and push new version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore(release): bump version to ${{ steps.bump.outputs.new }}"
          git tag "v${{ steps.bump.outputs.new }}"
          git push origin HEAD:main --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.new }}
          name: r2j v${{ steps.bump.outputs.new}}
          generate_release_notes: true
